### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by thrashor** [chrismaddalena/ODIN#28]
Running on Ubuntu 18.04.1 and am frequently running into the following error while running against some targets:

```
Process Employee Hunter:
Traceback (most recent call last):
  File "/home/cht/.local/share/virtualenvs/ODIN-M4UjiRTK/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cht/.local/share/virtualenvs/ODIN-M4UjiRTK/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cht/ODIN/lib/reporter.py", line 794, in create_people_table
    self.c.execute("INSERT INTO email_addresses VALUES (?,NULL,NULL)",(email,))
sqlite3.OperationalError: database is locked

```

**Comment by thrashor** [comment]
Was trying to dig into the problem further. Could there be an issue when no results are returned from Full Contact? See below:

```
[!] Full Contact returned no data for <redacted>.com.
L.. Details: database is locked

[+] Hunter has contact data for 10 people.
[+] Final unique findings: 23 emails, 10 people, 0 Twitter handles.
[+] Checking emails with HaveIBeenPwned. There is a 3 second delay between requests.

Process Employee Hunter:
Traceback (most recent call last):
  File "/home/cht/.local/share/virtualenvs/ODIN-M4UjiRTK/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cht/.local/share/virtualenvs/ODIN-M4UjiRTK/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cht/ODIN/lib/reporter.py", line 794, in create_people_table
    self.c.execute("INSERT INTO email_addresses VALUES (?,NULL,NULL)",(email,))
sqlite3.OperationalError: database is locked
```
